version: '3.8'

services:
  jupyter_lab:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"  # Map Jupyter Lab's default port to the host
    volumes:
      - .:/app  # Mounts the current directory into /app in the container