name: myenv
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - jupyterlab
  - pandas
  - scipy
  - scikit-learn
  - numpy
  - matplotlib
  - tensorflow
  - pytorch
  - torchvision
  - torchaudio
